name: Next.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: run hello action
        env:
          NEXT_PUBLIC_RESAS_API_KEY: ${{secrets.NEXT_PUBLIC_RESAS_API_KEY}}
          NEXT_PUBLIC_RESAS_API_URL: ${{secrets.NEXT_PUBLIC_RESAS_API_URL}}
          CYPRESS_RESAS_API_KEY: ${{secrets.CYPRESS_RESAS_API_KEY}}
          CYPRESS_RESAS_API_URL: ${{secrets.CYPRESS_RESAS_API_URL}}

      - name: Build
        run: yarn build

      - name: Jest Test
        run: yarn test

      - name: E2E Test
        run: yarn e2e:headless